04 ticket
StevenJune/steven-nc-news pull request #2
Opened 2022-09-28 08:57 UTC by StevenJune

2022-09-28 09:35 UTC, mallionaire requested changes
Hi Steven, 
You will not be able to use <table> for this project. 
Please change the way articles, users and topics are displayed to the user, you could use <h2>, <h3> ,<h4> and <p>

You will need to remove all your console.logs.
ReadArticlesByTopic.jsx is empty and has no code.

2022-09-28 09:35 UTC, mallionaire commented on src/App.js
> +//import { useState, useEffect } from "react";
Please do not include commented out code

2022-09-28 09:35 UTC, mallionaire commented on src/components/AllArticles.jsx
> +       console.log(response.statusText,'kkkkerror obj')
remove console.logs

2022-09-28 09:35 UTC, mallionaire commented on src/components/AllArticles.jsx
> +    <table>
Please use other html tags to display your information. You will not be able to use <table>

2022-09-28 09:35 UTC, mallionaire commented on src/components/Topics.jsx
> +import ReadArticlesByTopic from './ReadArticlesByTopic.jsx';
This is an empty file and causing an error in the console

2022-09-28 09:51 UTC, StevenJune commented
Hi Haz,
    I cannot read the below suggestions, it just show (see below) , which mean I cannot use <table> <th><tr><td></table>, right?
,
Thanks
Steven


________________________________
From: Haz M ***@***.***>
Sent: Wednesday, September 28, 2022 5:35 PM
To: StevenJune/steven-nc-news ***@***.***>
Cc: StevenJune ***@***.***>; Author ***@***.***>
Subject: Re: [StevenJune/steven-nc-news] 04 ticket (PR #2)


@mallionaire requested changes on this pull request.

Hi Steven,
You will not be able to use

for this project.
Please change the way articles, users and topics are displayed to the user, you could use
,
,
and

You will need to remove all your console.logs.
ReadArticlesByTopic.jsx is empty and has no code.

________________________________

In src/App.js<https://github.com/StevenJune/steven-nc-news/pull/2#discussion_r982161616>:

> @@ -1,24 +1,36 @@
 import logo from './logo.svg';
-import './App.css';
+import "./App.css";
+//import { useState, useEffect } from "react";


Please do not include commented out code

________________________________

In src/components/AllArticles.jsx<https://github.com/StevenJune/steven-nc-news/pull/2#discussion_r982168083>:

> +import axios from "axios";
+import SingleArticle from './SingleArticle.jsx';
+
+//import { Route, Routes } from 'react-router-dom';
+
+function AllArticles() {
+  const [articles, setArticles] = useState([]);
+  const [isLoading,setIsLoading] = useState(true);
+  const [isError, setIsError] = useState(false);
+  console.log('in All Articles');
+  useEffect(() => {
+   axios
+     .get("https://be-my-news-example.herokuapp.com/api/articles")
+     .then(function (response) {
+       // handle success
+       console.log(response.statusText,'kkkkerror obj')


remove console.logs

________________________________

In src/components/AllArticles.jsx<https://github.com/StevenJune/steven-nc-news/pull/2#discussion_r982169601>:

> +       if (!response.statusText === 'OK') {
+        setIsError(true)
+        setIsLoading(false);
+       } else {
+        console.log(response.data.articles);
+        setIsLoading(false);
+        setArticles(response.data.articles);
+       }
+     });
+  }, []);
+  console.log('end of useEffect')
+  if (isLoading) return <p>Loading...</p>;
+  if (isError) return <p>Error happening........</p>
+
+  return (
+    <table>


Please use other html tags to display your information. You will not be able to use

________________________________

In src/components/Topics.jsx<https://github.com/StevenJune/steven-nc-news/pull/2#discussion_r982171980>:

> @@ -0,0 +1,61 @@
+import { useState, useEffect } from "react";
+import axios from "axios";
+import ReadArticlesByTopic from './ReadArticlesByTopic.jsx';


This is an empty file and causing an error in the console

—
Reply to this email directly, view it on GitHub<https://github.com/StevenJune/steven-nc-news/pull/2#pullrequestreview-1123329141>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZJTT3WJY7H2EF7EMXEPIE3WAQGPZANCNFSM6AAAAAAQXRUG7I>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-09-28 11:14 UTC, Augs0 requested changes
As discussed in our messages on Slack, please change from a table to another html tag to display your data. Table formats are outdated and also now used only for its proper use: displaying data

2022-09-29 08:34 UTC, Rayhaan2k9 commented on src/components/AllArticles.jsx
> +        console.log(response.data.articles);
Please remove the console log

2022-09-29 08:36 UTC, Rayhaan2k9 commented on src/components/ReadArticlesByTopic.jsx
> +export default ReadArticlesByTopic;
If this file is empty, there is no need to commit it

2022-09-29 08:36 UTC, Rayhaan2k9 commented on src/components/SingleArticle.jsx
> +       console.log(response.statusText,'response obj from singlearticle')
Please remove the console log

2022-09-29 08:37 UTC, Rayhaan2k9 commented on src/components/SingleArticle.jsx
> +        console.log(response.data.articles);
Please remove the console log

2022-09-29 08:38 UTC, Rayhaan2k9 commented on src/components/Topics.jsx
> +        console.log(response.data.topics);
Please remove console log

2022-09-29 08:38 UTC, Rayhaan2k9 commented on src/components/Users.jsx
> +//   const [isError, setIsError] = useState(false);
Please remove these commented out code

2022-09-29 08:38 UTC, Rayhaan2k9 commented on src/components/Users.jsx
> +  console.log('end of useEffect')
Please remove the console log

2022-09-29 08:39 UTC, Rayhaan2k9 commented on src/components/Users.jsx
> +//</div>
Please remove the commented out code

2022-09-29 08:39 UTC, Rayhaan2k9 requested changes
Looking better now. Just need to remove the console logs and commented out code :)

2022-09-29 10:38 UTC, Augs0 approved these changes
Hi Steven, I'm approving as we can now see all articles and they are not in a table :) well done! The layout you have does need some fixing to work on all screen sizes as the list of articles hangs off the screen on smaller devices, but this is something you can fix later

2022-09-29 10:41 UTC, merged